### ISSUE TITLE
No such module 'ObjectMapper'

### ISSUE THREAD

**Issue by Nikohtr** [spaz926/Trivia-Swift#5]
When I try to build the project it says: No such module 'ObjectMapper'
<img width="708" alt="screen shot 2018-05-27 at 19 20 06" src="https://user-images.githubusercontent.com/25751483/40588251-4dc633c0-61e3-11e8-88e1-b2ae55275e5e.png">
<img width="1280" alt="screen shot 2018-05-27 at 19 21 58" src="https://user-images.githubusercontent.com/25751483/40588253-5149d308-61e3-11e8-976a-bcbaee10c7e4.png">

**Comment by spaz926** [comment]
I'm going to close this in favor of this issue:
